import { useState, useEffect } from 'react';
import { getSymbols, getIssues } from '../services/api';
import MetricCard from '../components/ui/MetricCard';
import { Bug, Activity, ShieldAlert, Binary } from 'lucide-react';
import './Dashboard.css';

export default function Dashboard() {
  const [metrics, setMetrics] = useState({
    symbols: 0,
    issues: 0,
    critical: 0,
    functions: 0
  });

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const [symData, issueData] = await Promise.all([
          getSymbols(),
          getIssues()
        ]);
        
        const functions = symData.symbols.filter(s => s.category === 'function').length;
        const critical = issueData.issues.filter(i => i.severity_label === 'critical').length;

        setMetrics({
          symbols: symData.total_symbols || 0,
          issues: issueData.total_issues || 0,
          critical,
          functions
        });
      } catch (err) {
        console.error('Failed to load dashboard data', err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  if (loading) return <div className="loading">Loading metrics...</div>;

  return (
    <div className="dashboard-container">
      <header className="page-header">
        <h1>Dashboard</h1>
        <p>CodeMaster Analysis Overview</p>
      </header>
      
      <div className="metrics-grid">
        <MetricCard
          title="Total Symbols"
          value={metrics.symbols}
          label="Variables & Structures"
          icon={Binary}
          glowColor="primary"
        />
        <MetricCard
          title="Functions"
          value={metrics.functions}
          label="Tracked routines"
          icon={Activity}
          glowColor="secondary"
        />
        <MetricCard
          title="Static Issues"
          value={metrics.issues}
          label="Total detected"
          icon={Bug}
          glowColor="medium"
        />
        <MetricCard
          title="Critical Issues"
          value={metrics.critical}
          label="Requires attention"
          icon={ShieldAlert}
          glowColor="critical"
        />
      </div>

      <div className="dashboard-content ethereal-card">
        <h3>System Status</h3>
        <p style={{ marginTop: '1rem', color: 'var(--color-on-surface-variant)' }}>
          All analysis hooks are running locally. Data is read from the `output/` directory generated by the C backend.
        </p>
      </div>
    </div>
  );
}
